name: Check for Pre-commit Hook Updates

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-hooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Check for pre-commit hook updates
        run: |
          pre-commit autoupdate
          if git diff --quiet .pre-commit-config.yaml; then
            echo "No updates found for pre-commit hooks."
            exit 0
          else
            echo "Updates found for pre-commit hooks."
          fi

      - name: Checkout master branch
        run: |
          git fetch origin master
          git checkout master

      - name: Create and Push Branch from Master
        run: |
          BRANCH_NAME="update-pre-commit-hooks-$(date +'%Y%m%d')"
          git checkout -b $BRANCH_NAME
          git add .pre-commit-config.yaml
          git commit -m "chore(pre-commit): update hooks to the latest versions" || echo "No changes to commit, but proceeding"
          git push --set-upstream origin $BRANCH_NAME
          git fetch origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update pre-commit hooks"
          body: "This PR updates pre-commit hooks to the latest versions."
          base: master
          branch: ${{ env.branch_name }}
