name: Update pre-commit hook

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-hooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Update only pre-commit hook
        run: |
          pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks

          if git diff --quiet .pre-commit-config.yaml; then
            echo "No updates found for pre-commit hooks."
            exit 0
          else
            echo "Updates found for pre-commit hooks."
          fi

          $PRE_COMMIT_VERSION=$(grep -A1 "https://github.com/pre-commit/pre-commit-hooks" .pre-commit-config.yaml | grep "rev:" | awk '{print $2}')
          echo "Updated pre-comit version: $PRE_COMMIT_VERSION"
          echo "pre_commit_version=$PRE_COMMIT_VERSION" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "ci(pre-commit): update pre-commit hook version to ${{ env.pre_commit_version }}"
          body: "This PR updates pre-commit hook to the latest version."
          base: master
          branch: "update-pre-commit-hook-${{ env.pre_commit_version }}"
          commit-message: "ci(pre-commit): update pre-commit hook version to ${{ env.pre_commit_version }}"
          delete-branch: true
